stages:
  - deploy

deploy_staging:
  stage: deploy
  image: kroniak/ssh-client:3.6
  script:
    - 'which ssh-agent || ( apk add openssh-client -y )'
    # add the server as a known host
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS"
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    # - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')
    #- echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    #- chmod 400 ~/.ssh/id_rsa
    # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # stop container, remove image.
    - ssh deployer@git.chaos.li -vvvvv
    - ssh deployer@git.chaos.li "cd /home/web/howto.c3roc.de"
    - ssh deployer@git.chaos.li "git pull chaos master" || true
    - ssh deployer@git.chaos.li "docker-compose stop" || true
    # start new container
    - ssh deployer@git.chaos.li "docker-compose up -d" || true
  only:
    - branches