stages:
  - deploy

deploy_staging:
  stage: deploy
  image: kroniak/ssh-client:3.6
  script:
    - 'which ssh-agent || ( apk add openssh-client -y )'
    # add the server as a known host
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # stop container, remove image.
    - ssh -p 2342 deployer@git.chaos.li "cd /home/html/howto.c3roc.de && git pull chaos master" || true
    - ssh -p 2342 deployer@git.chaos.li "docker-compose -f /home/html/howto.c3roc.de/docker-compose.yml stop" || true
    # start new container
    - ssh -p 2342 deployer@git.chaos.li "docker-compose -f /home/html/howto.c3roc.de/docker-compose.yml up -d" || true
  only:
    - branches